
# Jekyll theme
remote_theme: just-the-docs/just-the-docs

# Enable mermaid diagrams
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.0"
